import os
import shutil
from collections.abc import Iterator
from pathlib import Path
from typing import BinaryIO

from app.services.storage.base import ObjectNotFoundError

_CHUNK_SIZE = 64 * 1024


class LocalFileStorage:
    """Stores objects as files under a root directory.

    For local development and single-machine setups (a Docker volume in docker-compose).
    Production uses S3ObjectStorage; both implement the same ObjectStorage interface.
    """

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # Keys are generated by the app, but never let one escape the storage root.
        if not path.is_relative_to(self.root):
            raise ValueError(f"Invalid object key: {key!r}")
        return path

    def ensure_bucket(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)

    def put(self, key: str, data: BinaryIO, *, content_type: str, size: int) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a temp file and rename, so a crash never leaves a half-written resume.
        tmp = path.with_name(f".{path.name}.tmp")
        with tmp.open("wb") as out:
            shutil.copyfileobj(data, out, _CHUNK_SIZE)
        os.replace(tmp, path)

    def stream(self, key: str) -> Iterator[bytes]:
        path = self._path(key)
        try:
            handle = path.open("rb")
        except FileNotFoundError as exc:
            raise ObjectNotFoundError(key) from exc

        def chunks() -> Iterator[bytes]:
            with handle:
                while chunk := handle.read(_CHUNK_SIZE):
                    yield chunk

        return chunks()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)
